### ISSUE TITLE
Windows test errors

### ISSUE THREAD

**Issue by isuruf** [aleaxit/gmpy#153]
I get the following with MPIR, MPFR and MPC with MSVC on windows.
```
**********************************************************************
File "test_misc.txt", line 68, in test_misc.txt
Failed example:
    gmpy2._printf("%Zl", gmpy2.mpz(1))
Differences (ndiff with -expected +actual):
    + '%Zl'
    - Traceback (most recent call last):
    -   File "<stdin>", line 1, in <module>
    - ValueError: ** message detail varies **
**********************************************************************
File "test_misc.txt", line 80, in test_misc.txt
Failed example:
    gmpy2._printf("%.5RN", gmpy2.mpfr(1.23))
Differences (ndiff with -expected +actual):
    + '%.5RN'
    - Traceback (most recent call last):
    -   File "<stdin>", line 1, in <module>
    - ValueError: ** message detail varies **
**********************************************************************
1 items had failures:
   2 of  34 in test_misc.txt
```
With msys2 gmp, mpfr and mpc, this error is not there

**Comment by isuruf** [comment]
This is probably a MPIR or MPFR issue

**Comment by isuruf** [comment]
I guess not. `mpfr_asprintf` is supposed to return a negative integer when the string cannot be formatted, but in this case, it returns the formatting string and therefore an error is not thrown by gmpy2

**Comment by casevh** [comment]
What version of MPFR are you using? 

gmpy2.mpfr_version()

If it is the latest MPFR dev branch, they made some changes to mpfr_asprintf.

**Comment by isuruf** [comment]
`MPFR 4.0.0-dev`. This is from BrianGladman's repo a while back.

**Comment by casevh** [comment]
I can reproduce the error on Linux using MPIR 3.0.0, MPFR 4.0.0-dev, and MPC 1.1dev. It's not related to the recent WIndows changes.

I'll will get it fixed but I won't let it delay the first alpha release.

**Comment by isuruf** [comment]
No problem. Thanks for looking into this.
