### ISSUE TITLE
Reference count error with implicit __mpz__ conversion

### ISSUE THREAD

**Issue by casevh** [aleaxit/gmpy#235]
I just spotted an error in the implicit conversion of types implementing __mpz__. The following code continues to increase the reference count.

`>>> class A():
...   def __mpz__(self):
...     return "a"*len("aa")
... 
>>> gmpy2.mpz(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'str' can not be interpreted as mpz
[67012 refs]
>>> gmpy2.mpz(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'str' can not be interpreted as mpz
[67013 refs]
>>> gmpy2.mpz(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'str' can not be interpreted as mpz
[67014 refs]
>>> gmpy2.mpz(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'str' can not be interpreted as mpz
[67015 refs]
>>> gmpy2.mpz(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'str' can not be interpreted as mpz
[67016 refs]
`
I haven't looked at it in detail yet.

**Comment by casevh** [comment]
@vinklein Can you take a look at this?

**Comment by casevh** [comment]
No worries. I have a fix.

**Comment by casevh** [comment]
Fixed.

**Comment by vinklein** [comment]
Ok thanks
