### ISSUE TITLE
Regression (memory usage) for rc1?

### ISSUE THREAD

**Issue by skirpichev** [aleaxit/gmpy#305]
To reproduce (CPython 3.9, Linux, x86):
```
$ ulimit -v $((512*1024))
$ pip install -U --upgrade-strategy eager diofant[gmpy]
$ python
>>> import diofant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/diofant/diofant/__init__.py", line 8, in <module>
    from .core import (Add, Atom, AtomicExpr, Basic, Catalan, Derivative, Dict,
  File "/home/sk/src/diofant/diofant/core/__init__.py", line 8, in <module>
    from .expr import Expr, AtomicExpr
  File "/home/sk/src/diofant/diofant/core/expr.py", line 4, in <module>
    from mpmath.libmp import mpf_log, prec_to_dps
  File "/home/sk/venv/dev/lib/python3.9/site-packages/mpmath/__init__.py", line 5, in <module>
    from .ctx_fp import FPContext
  File "/home/sk/venv/dev/lib/python3.9/site-packages/mpmath/ctx_fp.py", line 1, in <module>
    from .ctx_base import StandardBaseContext
  File "/home/sk/venv/dev/lib/python3.9/site-packages/mpmath/ctx_base.py", line 3, in <module>
    from .libmp.backend import xrange
  File "/home/sk/venv/dev/lib/python3.9/site-packages/mpmath/libmp/__init__.py", line 17, in <module>
    from .libmpc import (mpc_one, mpc_zero, mpc_two, mpc_half,
  File "/home/sk/venv/dev/lib/python3.9/site-packages/mpmath/libmp/libmpc.py", line 23, in <module>
    from .libelefun import (\
  File "/home/sk/venv/dev/lib/python3.9/site-packages/mpmath/libmp/libelefun.py", line 76, in <module>
    cache_prec_steps += [min(2**k,LOG_TAYLOR_PREC)+20] * 2**(k-1)
MemoryError
```
Without gmpy2 this import works (try e.g. `DIOFANT_GROUND_TYPES=python python`).

**Comment by isuruf** [comment]
Should be fixed in https://github.com/aleaxit/gmpy/pull/306

**Comment by skirpichev** [comment]
Yes, I think so...  That's why I don't hit this bug earlier (using the git version with the system gmp).  Thank you, I'll test to be sure.

**Comment by isuruf** [comment]
See also https://github.com/fredrik-johansson/mpmath/issues/513

**Comment by casevh** [comment]
Thanks for finding this.

I was reviewing the script and noticed that it hasn't been updated to use GMP 6.2.1 and it that it doesn't apply the patches to MPFR. Do you see any issues with using GMP 6.2.1 and the latest patches for MPFR?

**Comment by skirpichev** [comment]
Hmm, I've tested wheels, build for 3.9:
https://github.com/skirpichev/gmpy/actions/runs/1228221313#artifacts

Unfortunately, I'm able to reproduce issue.  I'll test gmp 6.2.1 build.

BTW, I suspect the build_wheels action wasn't used to build the release wheels.  Probably, it can (at least for linux/macos).

**Comment by skirpichev** [comment]
Ok, gmp 6.2.1 build does work.

**Comment by isuruf** [comment]
There seems to be issues with gmp built from source and gmp already in the docker image clashing.

```
2021-08-27T04:30:57.3905171Z configure: WARNING: ==========================================================
2021-08-27T04:30:57.3910248Z configure: WARNING: 'gmp.h' and 'libgmp' seem to have different versions or
2021-08-27T04:30:57.3914230Z configure: WARNING: we cannot run a program linked with GMP (if you cannot
2021-08-27T04:30:57.3914970Z configure: WARNING: see the version numbers above). A cause may be different
2021-08-27T04:30:57.3926745Z configure: WARNING: GMP versions with different ABI's or the use of --with-gmp
2021-08-27T04:30:57.3927756Z configure: WARNING: or --with-gmp-include with a system include directory
2021-08-27T04:30:57.3929759Z configure: WARNING: (such as /usr/include or /usr/local/include). Another
2021-08-27T04:30:57.3930643Z configure: WARNING: cause may be that LD_RUN_PATH is not honored (problem
2021-08-27T04:30:57.3931463Z configure: WARNING: seen under OpenBSD 6.6).
2021-08-27T04:30:57.3932406Z configure: WARNING: However since we can't use 'libtool' inside the configure,
2021-08-27T04:30:57.3933599Z configure: WARNING: we can't be sure. See 'config.log' for details.
2021-08-27T04:30:57.3934137Z configure: WARNING: CC="gcc"
2021-08-27T04:30:57.3935085Z configure: WARNING: CFLAGS="-Wall -Wmissing-prototypes -Wpointer-arith -O2 -fomit-frame-pointer -m64"
2021-08-27T04:30:57.3935885Z configure: WARNING: CPPFLAGS=""
2021-08-27T04:30:57.3936603Z configure: WARNING: LDFLAGS=" -Wl,--disable-new-dtags"
2021-08-27T04:30:57.3937366Z configure: WARNING: LIBS="-lgmp "
2021-08-27T04:30:57.3937878Z configure: WARNING: Temporary LD_RUN_PATH was "".
2021-08-27T04:30:57.3938370Z configure: WARNING: ==========================================================
2021-08-27T04:30:59.9995644Z checking for math/nearbyint... yes
```

**Comment by skirpichev** [comment]
It's the mpfr build.  I doubt it was related to the mpmath issue (it's mpz-related).

**Comment by casevh** [comment]
Hmm. I didn't write the original before_ci_build script. I think is assumes that GMP, MPFR, and MPC are not installed in the Docker image. We may need to install the versions compiled by before_ci_build into a separate directory and then point the gmpy2 build script to that directory. I'll follow up tomorrow.

**Comment by skirpichev** [comment]
@casevh, as I said before, I doubt it's a related issue.  Seems to be related with linking the 6.2.0 version.  In the  #307 it was updated and this works for me.  Tested on 3.9 (linux) x86.

I've not reverted the @isuruf patch, but I'm not sure if it's required.

**Comment by skirpichev** [comment]
Unfortunately, gmp can't be removed from the image.  But I don't think it's a problem.
