### ISSUE TITLE
[Regression] Illegal instruction during a multiplication

### ISSUE THREAD

**Issue by andrei-datcu** [aleaxit/gmpy#317]
**This only reproduces with 2.10rc1 (and only if installed from the binary wheel) and only on one Xeon Machine.**
During a multiplication/modulo chain (so sorry, but the math is a bit over my head to provide a simple to repro example) a xeon machine gets an illegal instruction.

Steps to reproduce:
1. Install:
```
gmpy2==2.1.0rc1
ecdsa==0.15
```
2. Run: `python -X faulthandler -c "from ecdsa import VerifyingKey" `

Output:
```
Fatal Python error: Illegal instruction

Current thread 0x00007f7ce2d9d740 (most recent call first):
  File "/usr/local/lib/python3.9/site-packages/ecdsa/ellipticcurve.py", line 324 in _double_with_z_1
  File "/usr/local/lib/python3.9/site-packages/ecdsa/ellipticcurve.py", line 339 in _double
  File "/usr/local/lib/python3.9/site-packages/ecdsa/ellipticcurve.py", line 371 in double
  File "/usr/local/lib/python3.9/site-packages/ecdsa/ellipticcurve.py", line 173 in __init__
  File "/usr/local/lib/python3.9/site-packages/ecdsa/ecdsa.py", line 296 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 790 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1058 in _handle_fromlist
  File "/usr/local/lib/python3.9/site-packages/ecdsa/keys.py", line 72 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 790 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/usr/local/lib/python3.9/site-packages/ecdsa/__init__.py", line 1 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 790 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<string>", line 1 in <module>
Illegal instruction
1
```

Interpreter version: **Python 3.9.1** running in a docker container, `FROM python:3.9.1-buster`
Cpu Info:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2420 0 @ 1.90GHz
stepping        : 7
microcode       : 0x1
cpu MHz         : 1899.999
cache size      : 16384 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tsc_adjust xsaveopt arat umip md_clear arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 3799.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2420 0 @ 1.90GHz
stepping        : 7
microcode       : 0x1
cpu MHz         : 1899.999
cache size      : 16384 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tsc_adjust xsaveopt arat umip md_clear arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 3799.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

```

The multiplication/modulo code is here:
https://github.com/tlsfuzzer/python-ecdsa/blob/python-ecdsa-0.15/src/ecdsa/ellipticcurve.py#L324

Please let me know if there's any more information I can provide. Thanks a bunch!

~~Later edit: Interestingly, this doesn't reproduce with `ecdsa 0.16.1`, but it does with `ecdsa 0.16.0`~~ (that's irrelevant though)
This doesn't reproduce if building from source. It seems the binary build of libgmp the wheel provides is broken for my machine

**Comment by andrei-datcu** [comment]
Here's a native dump stack as well:

```
#0  0x00007f096cb5e12c in __gmpn_tdiv_qr () from /usr/local/lib/python3.9/site-packages/gmpy2/../gmpy2.libs/libgmp-aab612b0.so.10.4.0
#1  0x00007f096cb2e250 in __gmpz_tdiv_r () from /usr/local/lib/python3.9/site-packages/gmpy2/../gmpy2.libs/libgmp-aab612b0.so.10.4.0
#2  0x00007f096cb23849 in __gmpz_fdiv_r () from /usr/local/lib/python3.9/site-packages/gmpy2/../gmpy2.libs/libgmp-aab612b0.so.10.4.0
#3  0x00007f096d4b9b27 in GMPy_Integer_ModWithType (x=0x7f096ca48990, xtype=1, y=0x7f096cac6d20, ytype=1, context=0x7f096d78c9b0) at src/gmpy2_mod.c:52
#4  0x00007f096e44319e in binary_op1 (op_slot=24, w=0x7f096cac6d20, v=0x7f096ca48990) at Objects/abstract.c:869
#5  binary_op (op_name=0x7f096e578272 "%", op_slot=24, w=0x7f096cac6d20, v=0x7f096ca48990) at Objects/abstract.c:898
#6  PyNumber_Remainder (v=0x7f096ca48990, w=0x7f096cac6d20) at Objects/abstract.c:1086
```

Seems the modulo triggers the crash

**Comment by casevh** [comment]
I think this i related to a quirk when compiling the GMP library included in the wheel. I've release rc2 that might resolve it. Can you test?

**Comment by casevh** [comment]
I have released gmpy2 2.1.0. Can you test it?

**Comment by casevh** [comment]
Are you able to test with gmpy2 2.1.0 or 2.1.1?

**Comment by casevh** [comment]
No response so closing.
